export default [
  {
    meta: 'Codigo',
    label: 'COD',
    field: 'codigo',
    centered: false,
    visible: true,
    width: 5,
    numeric: true,
    type: 'integer',
    usage: 'rw',
    idx: 0,
  },
  {
    meta: 'Fecha',
    label: 'FECH',
    field: 'fecha',
    centered: true,
    visible: true,
    width: '10',
    numeric: false,
    type: 'date',
    usage: 'rw',
    idx: 1,
  },
  {
    meta: 'Estado',
    label: 'ESTS',
    field: 'estado',
    centered: true,
    visible: false,
    width: 10,
    numeric: false,
    type: 'text',
    usage: 'rw',
    idx: 2,
  },
  {
    meta: 'Codigo Cliente',
    label: 'CCLI',
    field: 'codigo_cliente',
    centered: true,
    visible: true,
    width: 6,
    numeric: false,
    type: 'foreignKey1',
    usage: 'rw',
    idx: 3,
  },
  {
    meta: 'Distribuidor',
    label: 'DIST',
    field: 'distribuidor',
    centered: true,
    visible: true,
    width: 4,
    numeric: false,
    type: 'text',
    usage: 'rw',
    idx: 4,
  },
  {
    meta: 'Descuento Especial',
    label: 'DESC',
    field: 'descuento_especial',
    centered: false,
    visible: false,
    width: 12,
    numeric: true,
    type: 'percent',
    usage: 'rw',
    idx: 5,
  },
  {
    meta: 'Lista de Items',
    label: 'ITMS',
    field: 'lista_de_items',
    centered: true,
    visible: false,
    width: 4,
    numeric: true,
    type: 'JSON1',
    usage: 'rw',
    idx: 6,
  },
  {
    meta: 'Subtotal IVA 12%',
    label: 'IV12',
    field: 'subtotal_iva_12',
    centered: false,
    visible: false,
    width: 12,
    numeric: true,
    type: 'usd',
    usage: 'rw',
    idx: 7,
  },
  {
    meta: 'Subtotal IVA 0%',
    label: 'IV00',
    field: 'subtotal_iva_0',
    centered: false,
    visible: false,
    width: 12,
    numeric: true,
    type: 'usd',
    usage: 'rw',
    idx: 8,
  },
  {
    meta: 'Subtotal Descontado',
    label: 'STDC',
    field: 'subtotal_descontado',
    centered: false,
    visible: false,
    width: 12,
    numeric: true,
    type: 'usd',
    usage: 'rw',
    idx: 9,
  },
  {
    meta: 'Total Calculado',
    label: 'TOTL',
    field: 'total_calculado',
    centered: false,
    visible: false,
    width: 12,
    numeric: true,
    type: 'usd',
    usage: 'rw',
    idx: 10,
  },
  {
    meta: 'Retenido',
    label: 'RETN',
    field: 'retenido',
    centered: false,
    visible: false,
    width: 12,
    numeric: true,
    type: 'usd',
    usage: 'rw',
    idx: 11,
  },
  {
    meta: 'Monto Final',
    label: 'MNTO',
    field: 'monto_final',
    centered: false,
    visible: true,
    width: 12,
    numeric: true,
    type: 'usd',
    usage: 'rw',
    idx: 12,
  },
  {
    meta: 'Total Cobrado',
    label: 'COBR',
    field: 'total_cobrado',
    centered: false,
    visible: false,
    width: 12,
    numeric: true,
    type: 'usd',
    usage: 'rw',
    idx: 13,
  },
];
