export default [
  {
    meta: 'Codigo',
    label: 'ID',
    field: 'codigo',
    centered: false,
    width: 5,
    visible: true,
    numeric: true,
  },
  {
    meta: 'RUC/Cedula',
    label: 'RUC',
    field: 'ruc_cedula',
    centered: false,
    width: 14,
    visible: true,
    numeric: false,
  },
  {
    meta: 'Nombre',
    label: 'NBR',
    field: 'nombre',
    centered: false,
    width: 70,
    visible: true,
    numeric: false,
  },
  {
    meta: 'Direcci\u00f3n',
    label: 'DIR',
    field: 'direccion',
    centered: false,
    width: '',
    visible: false,
    numeric: false,
  },
  {
    meta: 'Telefono',
    label: 'TLF',
    field: 'telefono',
    centered: false,
    width: 18,
    visible: true,
    numeric: false,
  },
  {
    meta: 'Distribuidor?',
    label: 'DST',
    field: 'distribuidor',
    centered: true,
    width: 3,
    visible: false,
    numeric: false,
  },
  {
    meta: 'Retencion?',
    label: 'RET',
    field: 'retencion',
    centered: true,
    width: 3,
    visible: false,
    numeric: false,
  },
  {
    meta: 'Tipo',
    label: 'TIP',
    field: 'tipo',
    centered: true,
    width: 3,
    visible: false,
    numeric: true,
  },
  {
    meta: 'Tipo de Documento',
    label: 'DOC',
    field: 'tipo_de_documento',
    centered: false,
    width: 27,
    visible: false,
    numeric: false,
  },
];
