export default [
  {
    meta: 'Codigo',
    label: 'ID',
    field: 'codigo',
    centered: false,
    width: 8,
    visible: true,
    type: 'integer',
    usage: 'rw',
    numeric: true,
    idx: 0,
  },
  {
    meta: 'Nombre',
    label: 'NBR',
    field: 'nombre',
    centered: true,
    width: 70,
    visible: true,
    type: 'title',
    usage: 'rw',
    numeric: false,
    idx: 1,
  },
  {
    meta: 'Unidad',
    label: 'UNI',
    field: 'unidad',
    centered: false,
    width: 16,
    visible: true,
    type: 'text',
    usage: 'rw',
    numeric: false,
    idx: 2,
  },
  {
    meta: 'IVA',
    label: 'IVA',
    field: 'iva',
    centered: false,
    width: '4',
    visible: true,
    type: 'percent',
    usage: 'r',
    numeric: true,
    idx: 3,
  },
  {
    meta: 'Valor',
    label: 'VAL',
    field: 'valor',
    centered: false,
    width: 10,
    visible: true,
    type: 'usd',
    usage: 'r',
    numeric: true,
    idx: 4,
  },
  {
    meta: 'Valor Distribuidor',
    label: 'VLD',
    field: 'valor_distribuidor',
    centered: false,
    width: 10,
    visible: false,
    type: 'usd',
    usage: 'r',
    numeric: true,
    idx: 5,
  },
  {
    meta: 'Porcentaje',
    label: 'PCT',
    field: 'porcentaje',
    centered: false,
    width: 4,
    visible: false,
    type: 'percent',
    usage: 'r',
    numeric: true,
    idx: 6,
  },
];
